### ISSUE TITLE
[minor] Errors on README

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#1]
I noticed some typos when reading the readme. For example, on the first sentence, you wrote "oun" instead of "own". Also, the registration process is called "register" not "registry". On the second paragraph, you mistook "hole" for "whole". I'm not quite sure what you meant with "everywhere the user can set tasks", if you meant on any section you should be more specific. Including technical names such as "taskLists" has no meaning for the user -- this should not be present in the end product. Almost at the end of the file, I noticed you forgot to include an Android showcase. Adding colons on a title doesn't looks good, like you did on the last two titles. Finally, you didn't wrote your name correctly, as it was signed as "Luas" instead of "Lucas". A common practice is to use the pronoun "them/they" when referring to the end user of an app, since is genderless. Remember that english differs from spanish when using pronouns.

NOTE: You also have misspellings overall -- please be more careful when submitting your work if you tend to have these grammatical errors. There are several tools which can help you being more clear, feel free to research and adjust them to your workspace.

**Comment by Lucastini** [comment]
Thank you for all these issues. I think i've fixed most of them.
