### ISSUE TITLE
[minor] Callback linking

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#10]
There is no need to use an anonymous function to link this callback here.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/27c993ed819ba8fac45042ba12d9d8fbd9a5ff5c/src/components/CheckBox/index.tsx#L49

**Comment by Lucastini** [comment]
Done! I also reviewed the other components and fixed the same mistake! Thanks!
