### ISSUE TITLE
[minor] Usage of ternaries

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#11]
Ternaries are not made to be handled in this way. Use if conditionals instead.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/27c993ed819ba8fac45042ba12d9d8fbd9a5ff5c/src/components/CheckBox/index.tsx#L43

**Comment by Lucastini** [comment]
Thanks!! Done!
