### ISSUE TITLE
[minor] Component naming

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#14]
Do not shortcut easily guessable names with short names. This is a bad practice and should only be used with custom components OR special scenarios, such as having multiple components with the same name. In practice, you can already infer it's a common TextInput from RN when using it's correct name.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/8db860ef037411ac9f969a5f81217ecff20487d1/src/components/Inputs/TextInput.tsx#L2

**Comment by Lucastini** [comment]
Done!
