### ISSUE TITLE
[minor] Prop type naming

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#16]
When working with a whole component prop types, you can easily name then just "Props". On general cases, it's adviced to follow the object name + type/interface, e.g. `TextContainerInterface`.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/8db860ef037411ac9f969a5f81217ecff20487d1/src/components/Inputs/TextInput.tsx#L5

**Comment by Lucastini** [comment]
Done!
