### ISSUE TITLE
[minor] Naming components

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#17]
Using common names as custom names it's a very bad practice. If you want to mimic or customize the behavior of a common component, use a more creative or specific name, such as `CustomTextInput`.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/8db860ef037411ac9f969a5f81217ecff20487d1/src/components/Inputs/TextInput.tsx#L12

**Comment by Lucastini** [comment]
Done!
