### ISSUE TITLE
[minor] Unnecesary variable

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#18]
Assigning to a variable a function with an specific return it's commonly a bad practice. If you want to work with the function's returned value, just call it each time you need to. For more advanced usage, you can set the value in a React Hook such as useMemo or useCallback.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/8db860ef037411ac9f969a5f81217ecff20487d1/src/components/Inputs/TextInput.tsx#L21

**Comment by Lucastini** [comment]
Done!
