### ISSUE TITLE
[suggestion] Usage of common constants

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#19]
When noticing common constants along the app, such as validating against the platform, you can transform them into a constant and place them on a file in your app, to have easy access.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/8db860ef037411ac9f969a5f81217ecff20487d1/src/components/Inputs/TextInput.tsx#L17

**Comment by Lucastini** [comment]
Done!
