### ISSUE TITLE
[suggestion] Usage of Expo

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#2]
We encourage not to use Expo library when making React Apps. It can be a severe disadvantage -- even a limiter on real world applications, since the libraries used need to be specific for the Expo environment, and you cannot work on all the functionalities present on a regular React Native app. We can accept this challenge as it is, but be aware that some of the corrections and opportunities present on this challenge might differ on the real job.

**Comment by Lucastini** [comment]
Thanks! As I´m working with a regular PC, android simulator hardly runs and my android cel phone´s batery was almost dying when y tryed to use it to compile connected by usb cable. Expo let me work without having a MAC but I´m sure I will also be able to dev with Native CLI after a little time of practice.

**Comment by ale1313** [comment]
As a personal experience, I know how hard can be to run Android on a Windows machine. You would probably want to get an alternative in the future -- maybe getting a MacBook for work, or choosing to create a osx VM, or the so called "Hackintosh". Most of these variants give you the opportunity to work on iOS, which is most requested than Android apps.
