### ISSUE TITLE
[minor] Usage of inline functions

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#20]
On most cases, it's adviced not to work with inline functions. Please create the function elsewhere in the same file, or use one of the React Hooks to make it more clear and performant.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/8db860ef037411ac9f969a5f81217ecff20487d1/src/components/Inputs/TextInput.tsx#L30

**Comment by Lucastini** [comment]
Done!
