### ISSUE TITLE
[CRITICAL] Disabling ts rules

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#21]
I request you to argument each of your disabled rules to have a better understanding of the problem with said lines.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/8db860ef037411ac9f969a5f81217ecff20487d1/src/components/LabelBox/LabelBox.tsx#L8

**Comment by Lucastini** [comment]
I implemented defaultProps in every component with no required props. It would be useful if you could help me a bit with what you seeI should adjust about esLint.
