### ISSUE TITLE
[minor] Mixture between english and spanish

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#3]
I noticed that some of the files present in this application are not following a language standard -- some of them are in spanish, while others are in english. This is discouraged on a final product, and can lead to misunderstanding. It's also a very unclean way to program without an actual standard. Please review your project one more time and make sure its written on a single language -- english, preferably.

**Comment by Lucastini** [comment]
Thanks! I checked all the code again and corrected many words. I guess I was mostly trying to get "working code" and didn't pay enough attention to orthography! Even though there are many corrections done, I will keep on working on this skill!
