### ISSUE TITLE
[minor] Inline styling

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#4]
I noticed some examples on your app where you inline style some components, e.g. `<SafeAreaView style={{flex: 1}}>`. While this is correct, it's a good practice to separate the style from the components on another file. This way, you can have a cleaner code.

**Comment by Lucastini** [comment]
Thanks! I checked every component and created a separated style file or a specific variable in components with very little style information. If its always better to create a separated file even in those cases I can go for it!!
