### ISSUE TITLE
[CRITICAL] Code linting

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#5]
While reviewing your code, I found that it's not correctly organized. Your code is messy, not standardized, and doesn't follow the best practices. If you cannot or don't know how to fix it, I can recommend you to get a code linter to help yourself with these tiny details that make a cleaner code. For example, some good tools are ESLint and TSLint, which can fix these errors automatically when saving.

**Comment by Lucastini** [comment]
Could you please give me more details of what you saw and what you suggest me? Even though there are utilities to automatically solve these errors I would prefere to learn how to structure my code properly! Thanks you very much for all your time!!!

**Comment by ale1313** [comment]
There are some things that separately doesn't matter much, but can make look your code look much more cleaner. For example, line breaks and their placement, indentation, unused code and variables, and many more. These errors won't crash your app, but certainly will improve the code readability. In my work experience I know that using some of these linters can help you save lots of time and effort without you having to re-read every single line -- with practice, you can even make clean code on the go. Here in DevLabs we follow AirBnb guidelines, and some of them are so specific that the linter won't pick up on the code; nonetheless, these practices can help you be more clear and even improve performance when done correctly, specially on big applications with thousands of lines of code. You might want to take a look at them: https://github.com/airbnb/javascript https://github.com/airbnb/javascript/tree/master/react

**Comment by Lucastini** [comment]
Thanks Alejo!! I added Eslinter and configured it with airbnb guide lines. There still may be some details to review but the code now mostly follows the requirements.
