### ISSUE TITLE
[CRITICAL] Writing props

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#7]
Props should NEVER be modified, they should be read-only.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/27c993ed819ba8fac45042ba12d9d8fbd9a5ff5c/src/components/CheckBox/index.tsx#L13

**Comment by Lucastini** [comment]
Done! I defined a default value as It's done for "color" prop, and destructured props in constants!
