### ISSUE TITLE
[suggestion] Props destructuring

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#8]
You can use ES6 object destructuring to get the props you want on the function's argument.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/27c993ed819ba8fac45042ba12d9d8fbd9a5ff5c/src/components/CheckBox/index.tsx#L12

**Comment by Lucastini** [comment]
Done! I thougth it was cleaner to do it separately. I kept only destructured props out of the function's argument on the components with numerous props, because I feel is easier to read but if its better to do it always in the function's argument I can go for It.
