### ISSUE TITLE
[CRITICAL] Value handling

### ISSUE THREAD

**Issue by ale1313** [Lucastini/RN_TaskManagerChallenge#9]
You should handle this validation on a React Hook, NEVER on the function instructions.

https://github.com/Lucastini/RN_TaskManagerChallenge/blob/27c993ed819ba8fac45042ba12d9d8fbd9a5ff5c/src/components/CheckBox/index.tsx#L21

**Comment by Lucastini** [comment]
Done! Its handled by a useEffect now! Thanks!
